import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import {
  servicesTable,
  ciRunsTable,
  flakyDetectionsTable,
  roiCalculationsTable,
  evidencePacketsTable,
  teamsTable,
} from "./schema/index.js";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is required for seeding");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

async function seed() {
  console.log("Seeding Performance Ledger database...");

  // --- Teams ---
  await db.insert(teamsTable).values([
    { id: "platform-engineering", name: "Platform Engineering", department: "Engineering" },
    { id: "citizen-services", name: "Citizen Services", department: "Product" },
    { id: "identity-access", name: "Identity & Access", department: "Security" },
    { id: "payments-team", name: "Payments Team", department: "Engineering" },
    { id: "document-services", name: "Document Services", department: "Engineering" },
    { id: "notification-platform", name: "Notification Platform", department: "Engineering" },
  ]).onConflictDoUpdate({
    target: teamsTable.id,
    set: { name: teamsTable.name, department: teamsTable.department },
  });
  console.log("  teams: seeded 6 rows");

  // --- Services (with computed scores) ---
  await db.insert(servicesTable).values([
    {
      id: "refund-status-api",
      name: "refund-status-api",
      tier: "TIER_1",
      status: "HEALTHY",
      missionReadiness: "READY",
      owner: "Platform Engineering",
      releaseCount: 14,
      lastUpdated: new Date("2026-05-28T06:00:00Z"),
      p50Latency: "42",
      p95Latency: "118",
      p99Latency: "210",
      errorRate: "0.12",
      throughput: 3420,
      score: "97.6",
      healthScore: 98,
      debtScore: 2,
      grade: "A",
      scoreDelta: "2.1",
      scoreTrend: "UP",
      recommendedAction: "Service is operating within all SLOs. Continue regular benchmarking cadence and maintain automation coverage above 80%.",
      compStability: "100",
      compRegressionFrequency: "100",
      compRegressionSeverity: "100",
      compTrend: "92",
      compTestCoverage: "88",
      compSignalReliability: "100",
      scoreDrivers: [],
    },
    {
      id: "taxpayer-account-portal",
      name: "taxpayer-account-portal",
      tier: "TIER_1",
      status: "WARNING",
      missionReadiness: "AT_RISK",
      owner: "Citizen Services",
      releaseCount: 9,
      lastUpdated: new Date("2026-05-28T05:45:00Z"),
      p50Latency: "210",
      p95Latency: "680",
      p99Latency: "1200",
      errorRate: "1.84",
      throughput: 8900,
      score: "45.2",
      healthScore: 45,
      debtScore: 55,
      grade: "F",
      scoreDelta: "-5.3",
      scoreTrend: "DOWN",
      recommendedAction: "1 releases blocked in the current window. Shift-left performance gates to the PR level to catch regressions before they reach the release pipeline.",
      compStability: "49.8",
      compRegressionFrequency: "15",
      compRegressionSeverity: "45",
      compTrend: "62",
      compTestCoverage: "61",
      compSignalReliability: "53.3",
      scoreDrivers: [],
    },
    {
      id: "identity-verification-service",
      name: "identity-verification-service",
      tier: "TIER_1",
      status: "CRITICAL",
      missionReadiness: "DEGRADED",
      owner: "Identity & Access",
      releaseCount: 6,
      lastUpdated: new Date("2026-05-28T04:30:00Z"),
      p50Latency: "890",
      p95Latency: "2400",
      p99Latency: "4100",
      errorRate: "4.21",
      throughput: 1250,
      score: "25.6",
      healthScore: 26,
      debtScore: 74,
      grade: "F",
      scoreDelta: "-8.9",
      scoreTrend: "DOWN",
      recommendedAction: "Error rate at 4.21% is the primary driver. Triage error sources, implement circuit-breaking if upstream dependent, and set a recovery gate before unblocking releases.",
      compStability: "16",
      compRegressionFrequency: "15",
      compRegressionSeverity: "45",
      compTrend: "35",
      compTestCoverage: "38",
      compSignalReliability: "5",
      scoreDrivers: [],
    },
    {
      id: "payment-plan-api",
      name: "payment-plan-api",
      tier: "TIER_2",
      status: "HEALTHY",
      missionReadiness: "READY",
      owner: "Payments Team",
      releaseCount: 18,
      lastUpdated: new Date("2026-05-28T07:00:00Z"),
      p50Latency: "68",
      p95Latency: "190",
      p99Latency: "340",
      errorRate: "0.28",
      throughput: 2100,
      score: "94",
      healthScore: 94,
      debtScore: 6,
      grade: "A",
      scoreDelta: "1.4",
      scoreTrend: "UP",
      recommendedAction: "Service is operating within all SLOs. Continue regular benchmarking cadence and maintain automation coverage above 80%.",
      compStability: "88",
      compRegressionFrequency: "100",
      compRegressionSeverity: "100",
      compTrend: "92",
      compTestCoverage: "82",
      compSignalReliability: "100",
      scoreDrivers: [],
    },
    {
      id: "document-upload-service",
      name: "document-upload-service",
      tier: "TIER_2",
      status: "WARNING",
      missionReadiness: "AT_RISK",
      owner: "Document Services",
      releaseCount: 7,
      lastUpdated: new Date("2026-05-28T05:15:00Z"),
      p50Latency: "320",
      p95Latency: "950",
      p99Latency: "1800",
      errorRate: "2.1",
      throughput: 540,
      score: "70",
      healthScore: 70,
      debtScore: 30,
      grade: "C",
      scoreDelta: "-3.2",
      scoreTrend: "DOWN",
      recommendedAction: "Error rate at 2.10% is the primary driver. Triage error sources, implement circuit-breaking if upstream dependent, and set a recovery gate before unblocking releases.",
      compStability: "37.8",
      compRegressionFrequency: "100",
      compRegressionSeverity: "100",
      compTrend: "62",
      compTestCoverage: "55",
      compSignalReliability: "57.5",
      scoreDrivers: [],
    },
    {
      id: "notice-delivery-service",
      name: "notice-delivery-service",
      tier: "TIER_2",
      status: "HEALTHY",
      missionReadiness: "READY",
      owner: "Notification Platform",
      releaseCount: 22,
      lastUpdated: new Date("2026-05-28T07:10:00Z"),
      p50Latency: "31",
      p95Latency: "88",
      p99Latency: "145",
      errorRate: "0.05",
      throughput: 4800,
      score: "98.2",
      healthScore: 98,
      debtScore: 2,
      grade: "A",
      scoreDelta: "3.8",
      scoreTrend: "UP",
      recommendedAction: "Service is operating within all SLOs. Continue regular benchmarking cadence and maintain automation coverage above 80%.",
      compStability: "100",
      compRegressionFrequency: "100",
      compRegressionSeverity: "100",
      compTrend: "92",
      compTestCoverage: "94",
      compSignalReliability: "100",
      scoreDrivers: [],
    },
  ]).onConflictDoUpdate({
    target: servicesTable.id,
    set: {
      status: servicesTable.status,
      missionReadiness: servicesTable.missionReadiness,
      score: servicesTable.score,
      healthScore: servicesTable.healthScore,
      debtScore: servicesTable.debtScore,
      grade: servicesTable.grade,
      scoreDelta: servicesTable.scoreDelta,
      scoreTrend: servicesTable.scoreTrend,
      p50Latency: servicesTable.p50Latency,
      p95Latency: servicesTable.p95Latency,
      p99Latency: servicesTable.p99Latency,
      errorRate: servicesTable.errorRate,
      throughput: servicesTable.throughput,
      lastUpdated: servicesTable.lastUpdated,
    },
  });
  console.log("  services: seeded 6 rows");

  // --- CI Runs (Releases) ---
  await db.insert(ciRunsTable).values([
    { id: "rel-001", serviceId: "refund-status-api", serviceName: "refund-status-api", version: "v2.4.1", governanceStatus: "APPROVED", createdAt: new Date("2026-05-27T10:00:00Z"), deployedAt: new Date("2026-05-27T14:22:00Z"), blockReason: null, debtScoreAtRelease: "28" },
    { id: "rel-002", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal", version: "v1.9.3", governanceStatus: "BLOCKED", createdAt: new Date("2026-05-26T09:00:00Z"), deployedAt: null, blockReason: "P95 latency exceeds 600ms SLO threshold", debtScoreAtRelease: "61" },
    { id: "rel-003", serviceId: "identity-verification-service", serviceName: "identity-verification-service", version: "v3.1.0", governanceStatus: "BLOCKED", createdAt: new Date("2026-05-25T08:00:00Z"), deployedAt: null, blockReason: "Error rate 4.2% exceeds 1% threshold — pending remediation", debtScoreAtRelease: "74" },
    { id: "rel-004", serviceId: "payment-plan-api", serviceName: "payment-plan-api", version: "v4.0.2", governanceStatus: "APPROVED", createdAt: new Date("2026-05-27T11:00:00Z"), deployedAt: new Date("2026-05-27T15:10:00Z"), blockReason: null, debtScoreAtRelease: "35" },
    { id: "rel-005", serviceId: "document-upload-service", serviceName: "document-upload-service", version: "v2.2.0", governanceStatus: "PENDING", createdAt: new Date("2026-05-28T07:00:00Z"), deployedAt: null, blockReason: null, debtScoreAtRelease: "52" },
    { id: "rel-006", serviceId: "notice-delivery-service", serviceName: "notice-delivery-service", version: "v5.1.4", governanceStatus: "APPROVED", createdAt: new Date("2026-05-28T06:30:00Z"), deployedAt: new Date("2026-05-28T09:00:00Z"), blockReason: null, debtScoreAtRelease: "19" },
    { id: "rel-007", serviceId: "refund-status-api", serviceName: "refund-status-api", version: "v2.4.0", governanceStatus: "APPROVED", createdAt: new Date("2026-05-20T10:00:00Z"), deployedAt: new Date("2026-05-20T13:00:00Z"), blockReason: null, debtScoreAtRelease: "31" },
    { id: "rel-008", serviceId: "payment-plan-api", serviceName: "payment-plan-api", version: "v3.9.8", governanceStatus: "BYPASSED", createdAt: new Date("2026-05-15T10:00:00Z"), deployedAt: new Date("2026-05-15T10:45:00Z"), blockReason: null, debtScoreAtRelease: "38" },
    { id: "rel-009", serviceId: "notice-delivery-service", serviceName: "notice-delivery-service", version: "v5.1.3", governanceStatus: "APPROVED", createdAt: new Date("2026-05-22T08:00:00Z"), deployedAt: new Date("2026-05-22T10:00:00Z"), blockReason: null, debtScoreAtRelease: "20" },
    { id: "rel-010", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal", version: "v1.9.2", governanceStatus: "APPROVED", createdAt: new Date("2026-05-10T10:00:00Z"), deployedAt: new Date("2026-05-10T14:00:00Z"), blockReason: null, debtScoreAtRelease: "55" },
  ]).onConflictDoUpdate({
    target: ciRunsTable.id,
    set: { governanceStatus: ciRunsTable.governanceStatus, deployedAt: ciRunsTable.deployedAt },
  });
  console.log("  ci_runs: seeded 10 rows");

  // --- Flaky Detections ---
  await db.insert(flakyDetectionsTable).values([
    {
      id: "flk-001", serviceId: "identity-verification-service", serviceName: "identity-verification-service",
      benchmark: "p99-latency-gate", flakinessScore: "72.8", flakyRiskScore: "72.8", flakyLabel: "Flaky",
      confidence: "VERY_LOW", primaryCause: "External identity provider response time variance",
      gateRecommendation: "Quarantine from hard-blocking gates — treat as informational signal only",
      remediationRecommendation: "Introduce a synthetic stub for external dependencies in benchmark context. Re-run against stub to isolate service performance.",
      executiveSummary: "The p99-latency-gate gate on identity-verification-service cannot be trusted as a release blocker. It is producing results inconsistent with actual service behavior and is blocking valid releases.",
      developerNote: "Top contributors: flip rate 88% on same commit; high metric variance (CV 90%); baseline drift 85%. Root: External identity provider response time variance.",
      compSameCommitFlipRate: "88", compMetricVarianceScore: "90", compRunnerNoiseScore: "20",
      compBaselineDriftScore: "85", compNearThresholdFailureRate: "82", compRerunDisagreementRate: "78",
      status: "OPEN", severity: "CRITICAL", affectedRuns: 41, totalRuns: 100,
      description: "P99 latency exceeds 4000ms on 41% of benchmark runs due to external ID provider variability",
      detectedAt: new Date("2026-05-26T12:00:00Z"),
    },
    {
      id: "flk-002", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal",
      benchmark: "throughput-under-load", flakinessScore: "55.4", flakyRiskScore: "55.4", flakyLabel: "Noisy",
      confidence: "LOW", primaryCause: "Connection pool exhaustion under simulated peak load",
      gateRecommendation: "Rerun on dedicated runner; do not block on single failure — require majority pass",
      remediationRecommendation: "Profile connection pool under benchmark load. Increase pool size or reduce benchmark concurrency to find saturation point.",
      executiveSummary: "The throughput-under-load gate on taxpayer-account-portal produces inconsistent results. Single failures should not block releases — require majority-pass before acting on results.",
      developerNote: "Top contributors: flip rate 55% on same commit; high metric variance (CV 72%); runner noise score 45. Root: Connection pool exhaustion under simulated peak load.",
      compSameCommitFlipRate: "55", compMetricVarianceScore: "72", compRunnerNoiseScore: "45",
      compBaselineDriftScore: "48", compNearThresholdFailureRate: "52", compRerunDisagreementRate: "58",
      status: "INVESTIGATING", severity: "HIGH", affectedRuns: 29, totalRuns: 50,
      description: "Throughput drops >30% under simulated peak load — possible connection pool exhaustion",
      detectedAt: new Date("2026-05-25T09:00:00Z"),
    },
    {
      id: "flk-003", serviceId: "document-upload-service", serviceName: "document-upload-service",
      benchmark: "error-rate-gate", flakinessScore: "42.5", flakyRiskScore: "42.5", flakyLabel: "Watch",
      confidence: "MODERATE", primaryCause: "Storage backend intermittency during multipart upload",
      gateRecommendation: "Keep as soft gate; require 2-of-3 passing runs before blocking",
      remediationRecommendation: "Profile connection pool under benchmark load. Increase pool size or reduce benchmark concurrency to find saturation point.",
      executiveSummary: "The error-rate-gate gate on document-upload-service shows early signs of noise. It is still usable for release governance but requires monitoring to prevent false blocks.",
      developerNote: "Top contributors: flip rate 42% on same commit; high metric variance (CV 55%). Root: Storage backend intermittency during multipart upload.",
      compSameCommitFlipRate: "42", compMetricVarianceScore: "55", compRunnerNoiseScore: "38",
      compBaselineDriftScore: "32", compNearThresholdFailureRate: "48", compRerunDisagreementRate: "38",
      status: "OPEN", severity: "MEDIUM", affectedRuns: 22, totalRuns: 50,
      description: "Intermittent 503 errors from storage backend during multipart upload tests",
      detectedAt: new Date("2026-05-24T14:00:00Z"),
    },
    {
      id: "flk-004", serviceId: "refund-status-api", serviceName: "refund-status-api",
      benchmark: "p95-latency-gate", flakinessScore: "18.8", flakyRiskScore: "18.8", flakyLabel: "Stable",
      confidence: "HIGH", primaryCause: "JVM cold-start warm-up artifact (resolved)",
      gateRecommendation: "Keep as hard gate — benchmark is reliable and can block releases",
      remediationRecommendation: "No action required. Continue regular benchmarking cadence.",
      executiveSummary: "The p95-latency-gate gate on refund-status-api is reliable. Results are consistent across runs and the benchmark can be trusted to block releases when it fails.",
      developerNote: "Benchmark is operating normally. Primary cause was: JVM cold-start warm-up artifact (resolved).",
      compSameCommitFlipRate: "18", compMetricVarianceScore: "22", compRunnerNoiseScore: "28",
      compBaselineDriftScore: "12", compNearThresholdFailureRate: "15", compRerunDisagreementRate: "10",
      status: "RESOLVED", severity: "LOW", affectedRuns: 9, totalRuns: 50,
      description: "Resolved — JVM warm-up artifact in cold-start benchmark runs",
      detectedAt: new Date("2026-05-20T10:00:00Z"),
    },
    {
      id: "flk-005", serviceId: "identity-verification-service", serviceName: "identity-verification-service",
      benchmark: "error-rate-gate", flakinessScore: "72.5", flakyRiskScore: "72.5", flakyLabel: "Flaky",
      confidence: "VERY_LOW", primaryCause: "Identity cache expiry timing collision with benchmark window",
      gateRecommendation: "Quarantine from hard-blocking gates — treat as informational signal only",
      remediationRecommendation: "Pre-warm cache state before benchmark run. Add a cache readiness probe to the test harness.",
      executiveSummary: "The error-rate-gate gate on identity-verification-service cannot be trusted as a release blocker. It is producing results inconsistent with actual service behavior and is blocking valid releases.",
      developerNote: "Top contributors: flip rate 88% on same commit; high metric variance (CV 90%); baseline drift 80%. Root: Identity cache expiry timing collision with benchmark window.",
      compSameCommitFlipRate: "88", compMetricVarianceScore: "90", compRunnerNoiseScore: "25",
      compBaselineDriftScore: "80", compNearThresholdFailureRate: "75", compRerunDisagreementRate: "80",
      status: "OPEN", severity: "CRITICAL", affectedRuns: 36, totalRuns: 51,
      description: "Error rate gate fails intermittently when identity cache expires mid-test run",
      detectedAt: new Date("2026-05-27T08:00:00Z"),
    },
    {
      id: "flk-006", serviceId: "payment-plan-api", serviceName: "payment-plan-api",
      benchmark: "concurrent-request-gate", flakinessScore: "28", flakyRiskScore: "28", flakyLabel: "Stable",
      confidence: "HIGH", primaryCause: "Runner group infrastructure noise (confirmed, not service regression)",
      gateRecommendation: "Keep as hard gate — benchmark is reliable and can block releases",
      remediationRecommendation: "No action required. Continue regular benchmarking cadence.",
      executiveSummary: "The concurrent-request-gate gate on payment-plan-api is reliable. Results are consistent across runs and the benchmark can be trusted to block releases when it fails.",
      developerNote: "Benchmark is operating normally. Primary cause was: Runner group infrastructure noise (confirmed, not service regression).",
      compSameCommitFlipRate: "25", compMetricVarianceScore: "30", compRunnerNoiseScore: "55",
      compBaselineDriftScore: "10", compNearThresholdFailureRate: "12", compRerunDisagreementRate: "20",
      status: "SUPPRESSED", severity: "LOW", affectedRuns: 14, totalRuns: 52,
      description: "Suppressed — test infrastructure noise, not service regression",
      detectedAt: new Date("2026-05-18T11:00:00Z"),
    },
    {
      id: "flk-007", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal",
      benchmark: "p50-baseline", flakinessScore: "38.1", flakyRiskScore: "38.1", flakyLabel: "Watch",
      confidence: "MODERATE", primaryCause: "Cron job interference causing latency drift on shared runner",
      gateRecommendation: "Keep as soft gate; require 2-of-3 passing runs before blocking",
      remediationRecommendation: "Schedule benchmark runs outside of maintenance windows. Pin runner to avoid shared-resource contention.",
      executiveSummary: "The p50-baseline gate on taxpayer-account-portal shows early signs of noise. It is still usable for release governance but requires monitoring to prevent false blocks.",
      developerNote: "Top contributors: flip rate 35% on same commit; high metric variance (CV 42%); baseline drift 45%. Root: Cron job interference causing latency drift on shared runner.",
      compSameCommitFlipRate: "35", compMetricVarianceScore: "42", compRunnerNoiseScore: "38",
      compBaselineDriftScore: "45", compNearThresholdFailureRate: "38", compRerunDisagreementRate: "28",
      status: "OPEN", severity: "MEDIUM", affectedRuns: 17, totalRuns: 50,
      description: "P50 latency drifts above 200ms baseline on evening runs — possible cron job interference",
      detectedAt: new Date("2026-05-28T03:00:00Z"),
    },
  ]).onConflictDoUpdate({
    target: flakyDetectionsTable.id,
    set: {
      flakyLabel: flakyDetectionsTable.flakyLabel,
      flakyRiskScore: flakyDetectionsTable.flakyRiskScore,
      confidence: flakyDetectionsTable.confidence,
      status: flakyDetectionsTable.status,
    },
  });
  console.log("  flaky_detections: seeded 7 rows");

  // --- ROI Calculations ---
  await db.insert(roiCalculationsTable).values([
    { id: "roi-001", serviceId: "refund-status-api", serviceName: "refund-status-api", savingsUsd: "32400", incidentsPrevented: 5, automationCoverage: "88", timeReductionHrs: "42" },
    { id: "roi-002", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal", savingsUsd: "18600", incidentsPrevented: 4, automationCoverage: "61", timeReductionHrs: "28" },
    { id: "roi-003", serviceId: "identity-verification-service", serviceName: "identity-verification-service", savingsUsd: "9200", incidentsPrevented: 2, automationCoverage: "38", timeReductionHrs: "14" },
    { id: "roi-004", serviceId: "payment-plan-api", serviceName: "payment-plan-api", savingsUsd: "28900", incidentsPrevented: 6, automationCoverage: "82", timeReductionHrs: "38" },
    { id: "roi-005", serviceId: "document-upload-service", serviceName: "document-upload-service", savingsUsd: "14700", incidentsPrevented: 3, automationCoverage: "55", timeReductionHrs: "19" },
    { id: "roi-006", serviceId: "notice-delivery-service", serviceName: "notice-delivery-service", savingsUsd: "21000", incidentsPrevented: 3, automationCoverage: "94", timeReductionHrs: "31" },
  ]).onConflictDoUpdate({
    target: roiCalculationsTable.id,
    set: { savingsUsd: roiCalculationsTable.savingsUsd, incidentsPrevented: roiCalculationsTable.incidentsPrevented },
  });
  console.log("  roi_calculations: seeded 6 rows");

  // --- Evidence Packets ---
  await db.insert(evidencePacketsTable).values([
    {
      id: "evp-001", serviceId: "refund-status-api", serviceName: "refund-status-api",
      releaseId: "rel-001", releaseVersion: "v2.3.1", commitSha: "a3f8c1d4e9b2",
      generatedAt: new Date("2026-05-27T13:00:00Z"), status: "PASSED",
      eventType: "RELEASE_GATE_EVALUATION", decision: "ALLOWED",
      policyName: "performance-governance-v2", metricViolated: null, metricUnit: null,
      baselineValue: null, observedValue: null, deltaPercent: null,
      debtScoreAtRelease: "28", passed: 24, failed: 0, blocked: 0,
      confidence: "HIGH", signalTrustScore: "92", flakyRiskLabel: "Stable",
      estimatedEngineeringHoursSaved: "4.5", estimatedCloudWasteAvoided: "320",
      ownerTeam: "Financial Services Platform",
      recommendedAction: "Approved for production deployment. No remediation required.",
      auditHash: "90333ce10b802c8f5d4a1b4655bdf5dc77d5979f",
      notes: "All gates passed. P95 within SLO. Throughput stable across 24 benchmark runs.",
      approvedBy: "K. Nakamura",
    },
    {
      id: "evp-002", serviceId: "taxpayer-account-portal", serviceName: "taxpayer-account-portal",
      releaseId: "rel-002", releaseVersion: "v1.9.3", commitSha: "b7d2e9f1c4a8",
      generatedAt: new Date("2026-05-26T10:00:00Z"), status: "BLOCKED",
      eventType: "AUTOMATED_BLOCK", decision: "BLOCKED",
      policyName: "performance-governance-v2", metricViolated: "p95_latency_ms", metricUnit: "ms",
      baselineValue: "380", observedValue: "680", deltaPercent: "78.9",
      debtScoreAtRelease: "61", passed: 18, failed: 4, blocked: 2,
      confidence: "LOW", signalTrustScore: "45", flakyRiskLabel: "Noisy",
      estimatedEngineeringHoursSaved: "12", estimatedCloudWasteAvoided: "1840",
      ownerTeam: "Citizen Services",
      recommendedAction: "Resolve P95 latency regression before reattempting release. Isolate throughput benchmark to dedicated runner.",
      auditHash: "40bf94f3adecfc7739d62fa99c0115ec71367a00",
      notes: "P95 latency 680ms exceeds 500ms SLO. Signal is Noisy — rerun on dedicated runner recommended before treating as definitive.",
      approvedBy: null,
    },
    {
      id: "evp-003", serviceId: "identity-verification-service", serviceName: "identity-verification-service",
      releaseId: "rel-003", releaseVersion: "v4.1.0", commitSha: "c9a4b2e7f015",
      generatedAt: new Date("2026-05-25T09:00:00Z"), status: "BLOCKED",
      eventType: "AUTOMATED_BLOCK", decision: "BLOCKED",
      policyName: "identity-security-governance-v1", metricViolated: "error_rate_percent", metricUnit: "%",
      baselineValue: "0.5", observedValue: "3.2", deltaPercent: "540",
      debtScoreAtRelease: "74", passed: 12, failed: 8, blocked: 4,
      confidence: "VERY_LOW", signalTrustScore: "28", flakyRiskLabel: "Flaky",
      estimatedEngineeringHoursSaved: "24", estimatedCloudWasteAvoided: "5200",
      ownerTeam: "Identity & Access",
      recommendedAction: "Quarantine error-rate gate from release blocking. Investigate cache expiry collision. Rebuild baseline after 50 clean runs.",
      auditHash: "2bc65375dede487eaf8414d7e32544b2316dcc27",
      notes: "Error rate gate is Flaky (risk score 72.5). Gate cannot be trusted as a release blocker. Escalated to Identity & Access team. Production hold in effect.",
      approvedBy: null,
    },
    {
      id: "evp-004", serviceId: "payment-plan-api", serviceName: "payment-plan-api",
      releaseId: "rel-004", releaseVersion: "v3.0.2", commitSha: "d1f5c8a3b2e7",
      generatedAt: new Date("2026-05-27T14:00:00Z"), status: "PASSED",
      eventType: "RELEASE_GATE_EVALUATION", decision: "ALLOWED",
      policyName: "performance-governance-v2", metricViolated: null, metricUnit: null,
      baselineValue: null, observedValue: null, deltaPercent: null,
      debtScoreAtRelease: "35", passed: 22, failed: 0, blocked: 0,
      confidence: "HIGH", signalTrustScore: "89", flakyRiskLabel: "Stable",
      estimatedEngineeringHoursSaved: "3", estimatedCloudWasteAvoided: "280",
      ownerTeam: "Revenue Operations",
      recommendedAction: "Approved for production deployment. Monitor throughput for first 30 minutes post-deploy.",
      auditHash: "188c152155b8481d330c738ba78f4c1aacfde1f6",
      notes: "Clean run. Throughput improved 12% over baseline. Concurrent request gate passed at 99.7% success rate.",
      approvedBy: "M. Okafor",
    },
    {
      id: "evp-005", serviceId: "document-upload-service", serviceName: "document-upload-service",
      releaseId: "rel-005", releaseVersion: "v2.7.4", commitSha: "e4b3c1f8d9a2",
      generatedAt: new Date("2026-05-28T07:30:00Z"), status: "PENDING",
      eventType: "RELEASE_GATE_EVALUATION", decision: "WARNED",
      policyName: "performance-governance-v2", metricViolated: "error_rate_percent", metricUnit: "%",
      baselineValue: "0.8", observedValue: "1.4", deltaPercent: "75",
      debtScoreAtRelease: "52", passed: 16, failed: 2, blocked: 1,
      confidence: "MODERATE", signalTrustScore: "67", flakyRiskLabel: "Watch",
      estimatedEngineeringHoursSaved: "8", estimatedCloudWasteAvoided: "960",
      ownerTeam: "Document Management",
      recommendedAction: "Hold release pending storage backend patch verification. Rerun error-rate gate before promoting.",
      auditHash: "f893d01b3296ebab992e644a3b395b7fc6e10f80",
      notes: "Awaiting rerun of error-rate gate after storage backend patch. Signal is on Watch — intermittent 503s may resolve with infrastructure fix.",
      approvedBy: null,
    },
    {
      id: "evp-006", serviceId: "notice-delivery-service", serviceName: "notice-delivery-service",
      releaseId: "rel-006", releaseVersion: "v5.1.3", commitSha: "f2a7d9b1c3e8",
      generatedAt: new Date("2026-05-28T08:00:00Z"), status: "PASSED",
      eventType: "RELEASE_GATE_EVALUATION", decision: "ALLOWED",
      policyName: "performance-governance-v2", metricViolated: null, metricUnit: null,
      baselineValue: null, observedValue: null, deltaPercent: null,
      debtScoreAtRelease: "19", passed: 26, failed: 0, blocked: 0,
      confidence: "HIGH", signalTrustScore: "96", flakyRiskLabel: "Stable",
      estimatedEngineeringHoursSaved: "2.5", estimatedCloudWasteAvoided: "210",
      ownerTeam: "Notification Services",
      recommendedAction: "Approved for production deployment. Service is performing at highest governance tier.",
      auditHash: "f215eb827fab41c68383087f20b294be101df11d",
      notes: "Excellent. All latency and throughput SLOs met with margin. Debt score improved from 24 to 19 since last release.",
      approvedBy: "R. Patel",
    },
  ]).onConflictDoUpdate({
    target: evidencePacketsTable.id,
    set: {
      status: evidencePacketsTable.status,
      decision: evidencePacketsTable.decision,
      auditHash: evidencePacketsTable.auditHash,
    },
  });
  console.log("  evidence_packets: seeded 6 rows");

  console.log("Seeding complete.");
  await pool.end();
}

seed().catch((e) => {
  console.error("Seed failed:", e);
  pool.end();
  process.exit(1);
});
